version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/gbg_app

hooks:
  ApplicationStop:
    - location: scripts/application_st.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user