/* eslint-disable no-shadow */
/* eslint-disable no-unused-vars */

export type ValeriaCardKingdomsSetFilters = {
  base: boolean;
  crimsonSeas: boolean;
  flamesAndFrost: boolean;
  peasantsAndKnights: boolean; // exp04
  shadowvale: boolean;
  undeadSamurai: boolean; // exp
};

export enum ValeriaCardKingdomsCardBucket {
  ONE = 1,
  TWO,
  THREE,
  FOUR,
  FIVE,
  SIX,
  SEVEN,
  EIGHT,
  NINE,
  ELEVEN = 11,
  MONSTER,
}

export type ValeriaCardKingdomsCard = {
  name: string;
  imgSrc: string;
  sortOrder: number;
  set: keyof ValeriaCardKingdomsSetFilters;
  bucket: ValeriaCardKingdomsCardBucket;
};

export const ValeriaCardKingdomsCardData: ValeriaCardKingdomsCard[] = [
  {
    set: "base",
    name: "Barrens",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 1,
    imgSrc: "images/monster-barrens.jpg",
  },
  {
    set: "base",
    name: "Cavern",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 6.1,
    imgSrc: "images/monster-cavern.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Desert",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4.2,
    imgSrc: "images/monster-desert.jpg",
  },
  {
    set: "base",
    name: "Forest",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 3,
    imgSrc: "images/monster-forest.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Glacier",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 7.1,
    imgSrc: "images/monster-glacier.jpg",
  },
  {
    set: "base",
    name: "Hills",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 1,
    imgSrc: "images/monster-hills.jpg",
  },
  {
    set: "base",
    name: "Mountains",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 5,
    imgSrc: "images/monster-mountains.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Oasis",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4,
    imgSrc: "images/monster-oasis.jpg",
  },
  {
    set: "base",
    name: "Ruins",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 2,
    imgSrc: "images/monster-ruins.jpg",
  },
  {
    set: "base",
    name: "Swamp",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 5.1,
    imgSrc: "images/monster-swamp.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Tundra",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 5.2,
    imgSrc: "images/monster-tundra.jpg",
  },
  {
    set: "base",
    name: "Valley",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4,
    imgSrc: "images/monster-valley.jpg",
  },
  {
    set: "undeadSamurai",
    name: "Undead Samurai",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 3,
    imgSrc: "images/monster-undead-samurai.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Volcano",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 8.1,
    imgSrc: "images/monster-volcano.jpg",
  },
  {
    set: "base",
    name: "Cleric",
    bucket: ValeriaCardKingdomsCardBucket.ONE,
    sortOrder: 0,
    imgSrc: "images/cleric.jpg",
  },
  {
    set: "base",
    name: "Monk",
    bucket: ValeriaCardKingdomsCardBucket.ONE,
    sortOrder: 0,
    imgSrc: "images/01-monk.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Summoner",
    bucket: ValeriaCardKingdomsCardBucket.ONE,
    sortOrder: 0,
    imgSrc: "images/01-summoner.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Bard",
    bucket: ValeriaCardKingdomsCardBucket.TWO,
    sortOrder: 0,
    imgSrc: "images/02-bard.jpg",
  },
  {
    set: "base",
    name: "Blacksmith",
    bucket: ValeriaCardKingdomsCardBucket.TWO,
    sortOrder: 0,
    imgSrc: "images/02-blacksmith.jpg",
  },
  {
    set: "base",
    name: "Merchant",
    bucket: ValeriaCardKingdomsCardBucket.TWO,
    sortOrder: 0,
    imgSrc: "images/02-merchant.jpg",
  },
  {
    set: "base",
    name: "Alchemist",
    bucket: ValeriaCardKingdomsCardBucket.THREE,
    sortOrder: 0,
    imgSrc: "images/03-alchemist.jpg",
  },
  {
    set: "base",
    name: "Mercenary",
    bucket: ValeriaCardKingdomsCardBucket.THREE,
    sortOrder: 0,
    imgSrc: "images/03-mercenary.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Sorceress",
    bucket: ValeriaCardKingdomsCardBucket.THREE,
    sortOrder: 0,
    imgSrc: "images/03-sorceress.jpg",
  },
  {
    set: "base",
    name: "Archer",
    bucket: ValeriaCardKingdomsCardBucket.FOUR,
    sortOrder: 0,
    imgSrc: "images/04-archer.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Barbarian",
    bucket: ValeriaCardKingdomsCardBucket.FOUR,
    sortOrder: 0,
    imgSrc: "images/04-barbarian.jpg",
  },
  {
    set: "base",
    name: "Wizard",
    bucket: ValeriaCardKingdomsCardBucket.FOUR,
    sortOrder: 0,
    imgSrc: "images/04-wizard.jpg",
  },
  {
    set: "peasantsAndKnights",
    name: "Alt. Peasant",
    bucket: ValeriaCardKingdomsCardBucket.FIVE,
    sortOrder: 0,
    imgSrc: "images/05-alt-peasant.jpg",
  },
  {
    set: "base",
    name: "Peasant",
    bucket: ValeriaCardKingdomsCardBucket.FIVE,
    sortOrder: 0,
    imgSrc: "images/05-peasant.jpg",
  },
  {
    set: "peasantsAndKnights",
    name: "Alt. Knight",
    bucket: ValeriaCardKingdomsCardBucket.SIX,
    sortOrder: 0,
    imgSrc: "images/06-alt-knight.jpg",
  },
  {
    set: "base",
    name: "Knight",
    bucket: ValeriaCardKingdomsCardBucket.SIX,
    sortOrder: 0,
    imgSrc: "images/06-knight.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Condottiere",
    bucket: ValeriaCardKingdomsCardBucket.SEVEN,
    sortOrder: 0,
    imgSrc: "images/07-condottiere.jpg",
  },
  {
    set: "base",
    name: "Rogue",
    bucket: ValeriaCardKingdomsCardBucket.SEVEN,
    sortOrder: 0,
    imgSrc: "images/07-rogue.jpg",
  },
  {
    set: "base",
    name: "Thief",
    bucket: ValeriaCardKingdomsCardBucket.SEVEN,
    sortOrder: 0,
    imgSrc: "images/07-thief.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Bogatyr",
    bucket: ValeriaCardKingdomsCardBucket.EIGHT,
    sortOrder: 0,
    imgSrc: "images/08-bogatyr.jpg",
  },
  {
    set: "base",
    name: "Champion",
    bucket: ValeriaCardKingdomsCardBucket.EIGHT,
    sortOrder: 0,
    imgSrc: "images/08-champion.jpg",
  },
  {
    set: "base",
    name: "Warlord",
    bucket: ValeriaCardKingdomsCardBucket.EIGHT,
    sortOrder: 0,
    imgSrc: "images/08-warlord.jpg",
  },
  {
    set: "base",
    name: "Paladin",
    bucket: ValeriaCardKingdomsCardBucket.NINE,
    sortOrder: 0,
    imgSrc: "images/09-10-paladin.jpg",
  },
  {
    set: "base",
    name: "Priestess",
    bucket: ValeriaCardKingdomsCardBucket.NINE,
    sortOrder: 0,
    imgSrc: "images/09-10-priestess.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Templar",
    bucket: ValeriaCardKingdomsCardBucket.NINE,
    sortOrder: 0,
    imgSrc: "images/09-10-templar.jpg",
  },
  {
    set: "flamesAndFrost",
    name: "Baker",
    bucket: ValeriaCardKingdomsCardBucket.ELEVEN,
    sortOrder: 0,
    imgSrc: "images/11-12-baker.jpg",
  },
  {
    set: "base",
    name: "Butcher",
    bucket: ValeriaCardKingdomsCardBucket.ELEVEN,
    sortOrder: 0,
    imgSrc: "images/11-12-butcher.jpg",
  },
  {
    set: "base",
    name: "Miner",
    bucket: ValeriaCardKingdomsCardBucket.ELEVEN,
    sortOrder: 0,
    imgSrc: "images/11-12-miner.jpg",
  },
  {
    set: "shadowvale",
    name: "Crypt",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 5,
    imgSrc: "images/monster-crypt.png",
  },
  {
    set: "shadowvale",
    name: "Den",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4,
    imgSrc: "images/monster-den.png",
  },
  {
    set: "shadowvale",
    name: "Necropolis",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 2,
    imgSrc: "images/monster-necropolis.png",
  },
  {
    set: "shadowvale",
    name: "Sewer",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 2.1,
    imgSrc: "images/monster-sewer.png",
  },
  {
    set: "shadowvale",
    name: "Woods",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4.1,
    imgSrc: "images/monster-woods.png",
  },
  {
    set: "shadowvale",
    name: "Exorcist",
    bucket: ValeriaCardKingdomsCardBucket.ONE,
    sortOrder: 0,
    imgSrc: "images/01-exorcist.png",
  },
  {
    set: "shadowvale",
    name: "Lumberjack",
    bucket: ValeriaCardKingdomsCardBucket.TWO,
    sortOrder: 0,
    imgSrc: "images/02-lumberjack.png",
  },
  {
    set: "shadowvale",
    name: "Bandit",
    bucket: ValeriaCardKingdomsCardBucket.THREE,
    sortOrder: 0,
    imgSrc: "images/03-bandit.png",
  },
  {
    set: "shadowvale",
    name: "Hunter",
    bucket: ValeriaCardKingdomsCardBucket.FOUR,
    sortOrder: 0,
    imgSrc: "images/04-hunter.png",
  },
  {
    set: "shadowvale",
    name: "Peasant (magic)",
    bucket: ValeriaCardKingdomsCardBucket.FIVE,
    sortOrder: 0,
    imgSrc: "images/05-peasant-magic.png",
  },
  {
    set: "shadowvale",
    name: "Knight (gold)",
    bucket: ValeriaCardKingdomsCardBucket.SIX,
    sortOrder: 0,
    imgSrc: "images/06-knight-gold.png",
  },
  {
    set: "shadowvale",
    name: "Necromancer",
    bucket: ValeriaCardKingdomsCardBucket.SEVEN,
    sortOrder: 0,
    imgSrc: "images/07-necromancer.png",
  },
  {
    set: "shadowvale",
    name: "Guardian",
    bucket: ValeriaCardKingdomsCardBucket.EIGHT,
    sortOrder: 0,
    imgSrc: "images/08-guardian.png",
  },
  {
    set: "shadowvale",
    name: "Dragoon",
    bucket: ValeriaCardKingdomsCardBucket.NINE,
    sortOrder: 0,
    imgSrc: "images/09-10-dragoon.png",
  },
  {
    set: "shadowvale",
    name: "Inventor",
    bucket: ValeriaCardKingdomsCardBucket.ELEVEN,
    sortOrder: 0,
    imgSrc: "images/11-12-inventor.png",
  },
  {
    set: "crimsonSeas",
    name: "Hydromancer",
    bucket: ValeriaCardKingdomsCardBucket.ONE,
    sortOrder: 0,
    imgSrc: "images/01-hydromancer.png",
  },
  {
    set: "crimsonSeas",
    name: "Engineer",
    bucket: ValeriaCardKingdomsCardBucket.TWO,
    sortOrder: 0,
    imgSrc: "images/02-engineer.png",
  },
  {
    set: "crimsonSeas",
    name: "Vitki",
    bucket: ValeriaCardKingdomsCardBucket.THREE,
    sortOrder: 0,
    imgSrc: "images/03-vitki.png",
  },
  {
    set: "crimsonSeas",
    name: "Marauder",
    bucket: ValeriaCardKingdomsCardBucket.FOUR,
    sortOrder: 0,
    imgSrc: "images/04-marauder.png",
  },
  {
    set: "crimsonSeas",
    name: "Peasant (CS)",
    bucket: ValeriaCardKingdomsCardBucket.FIVE,
    sortOrder: 0,
    imgSrc: "images/05-peasant-cs.png",
  },
  {
    set: "crimsonSeas",
    name: "Knight (CS)",
    bucket: ValeriaCardKingdomsCardBucket.SIX,
    sortOrder: 0,
    imgSrc: "images/06-knight-cs.png",
  },
  {
    set: "crimsonSeas",
    name: "Smuggler",
    bucket: ValeriaCardKingdomsCardBucket.SEVEN,
    sortOrder: 0,
    imgSrc: "images/07-smuggler.png",
  },
  {
    set: "crimsonSeas",
    name: "Dreadnaught",
    bucket: ValeriaCardKingdomsCardBucket.EIGHT,
    sortOrder: 0,
    imgSrc: "images/08-dreadnaught.png",
  },
  {
    set: "crimsonSeas",
    name: "Conjurer",
    bucket: ValeriaCardKingdomsCardBucket.NINE,
    sortOrder: 0,
    imgSrc: "images/09-10-conjurer.png",
  },
  {
    set: "crimsonSeas",
    name: "Purser",
    bucket: ValeriaCardKingdomsCardBucket.ELEVEN,
    sortOrder: 0,
    imgSrc: "images/11-12-purser.png",
  },
  {
    set: "crimsonSeas",
    name: "Cutthroats",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 3.1,
    imgSrc: "images/monster-cutthroats.png",
  },
  {
    set: "crimsonSeas",
    name: "Dark Waters",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 3,
    imgSrc: "images/monster-dark-waters.png",
  },
  {
    set: "crimsonSeas",
    name: "Gloom Gyre",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 3.2,
    imgSrc: "images/monster-gloom-gyre.png",
  },
  {
    set: "crimsonSeas",
    name: "Skerry",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 4.1,
    imgSrc: "images/monster-skerry.png",
  },
  {
    set: "crimsonSeas",
    name: "The Deep",
    bucket: ValeriaCardKingdomsCardBucket.MONSTER,
    sortOrder: 2.1,
    imgSrc: "images/monster-the-deep.png",
  },
];

export const ValeriaCardKingdomsCardBuckets: { [key: string]: ValeriaCardKingdomsCard[]; } = {
  MONSTER: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.MONSTER),
  ONE: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.ONE),
  TWO: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.TWO),
  THREE: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.THREE),
  FOUR: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.FOUR),
  FIVE: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.FIVE),
  SIX: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.SIX),
  SEVEN: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.SEVEN),
  EIGHT: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.EIGHT),
  NINE: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.NINE),
  ELEVEN: ValeriaCardKingdomsCardData.filter((card) => card.bucket === ValeriaCardKingdomsCardBucket.ELEVEN),
};
